### ISSUE TITLE
Start Continuous Build Task Not Configured Properly

### ISSUE THREAD

**Issue by AndrewWeinmann** [kevinlyles/euchre#3]
Opening the Run Task menu in VS Code gives the following options, and the below text appears in the Output window.

![image](https://user-images.githubusercontent.com/15718061/37530105-dc2e9500-2906-11e8-9e19-d853263afce7.png)

> Error: The typescript task detection didn't contribute a task for the following configuration:
> {
>     "label": "Start continuous build",
>     "type": "typescript",
>     "tsconfig": "EuchreSolution/Euchre/tsconfig.json",
>     "option": "watch",
>     "problemMatcher": [
>         "$tsc-watch"
>     ],
>     "group": {
>         "kind": "build",
>         "isDefault": true
>     }
> }
> The task will be ignored.

**Comment by kevinlyles** [comment]
There doesn't appear to be a way to specify platform-specific paths for tsconfig.json.  The default task works well enough, so I think I might just take this task out.  All we're losing is defaulting to the watch task when you hit Ctrl+Shift+B (now you're prompted instead) and the more-consistent task name.
